version: '3.1'

services:

  wordpress:
    build: ./
    restart: always
    ports:
      - 8080:80
    hostname: wordpress
    extra_hosts:
      - "localhost localhost.localdomain wordpress:127.0.0.1"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: DB_USER
      WORDPRESS_DB_PASSWORD: DB_PASSWORD
      WORDPRESS_DB_NAME: DB_NAME
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: DB_NAME
      MYSQL_USER: DB_USER
      MYSQL_PASSWORD: DB_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
